/**
* @File Name : AccountHandler2.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : January 2, 2026
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | January 2, 2026 |   | Initial Version
**/

public class AccountHandler2 {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}